# Generated by Django 3.1.7 on 2021-03-04 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockApp', '0003_auto_20210304_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='shares_quantity',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
