# Generated by Django 3.1.7 on 2021-03-05 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockApp', '0004_auto_20210304_2117'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
